# docker-compose up -d db mq
# docker exec -it basic-postgres /bin/sh
# docker-compose down
version: '3.8'
services:
  db:
    # image: postgres:14.1-alpine
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      # - db:/var/lib/postgresql/data
      - ./db:/db
  mq:
    image: rabbitmq:3-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes: []

volumes:
  db:
    driver: local