# docker-compose up -d
# docker exec -it basic-postgres /bin/sh
# docker-compose down
version: '3.8'
services:
  db:
    # image: postgres:14.1-alpine
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      # - db:/var/lib/postgresql/data
      - ./db:/db
volumes:
  db:
    driver: local